[package]
name = "super_orchestrator"
version = "0.8.0"
edition = "2021"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/super_orchestrator"
documentation = "https://docs.rs/super_orchestrator"
keywords = ["container", "docker"]
description = "programmable container orchestration tools"

[dependencies]
clap = "4"
ctrlc = { version = "3", optional = true, default-features = false }
env_logger = { version = "0.10", optional = true, default-features = false }
log = "0.4"
nix = { version = "0.27", optional = true, default-features = false, features = ["signal"] }
owo-colors = { version = "3.5", default-features = false }
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1.0" }
sha3 = "0.10"
stacked_errors = { version = "0.5", default-features = false }
#stacked_errors = { git = "https://github.com/AaronKutch/stacked_errors", rev = "74d52fd24ff7ec1faab4f2065f37ff356f089137", default-features = false }
#stacked_errors = { path = "../stacked_errors", default-features = false }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
clap = { version = "4", features = ["derive", "env"] }
serde_json = { version = "1.0" }

[features]
default = ["ctrlc_support", "env_logger_support", "nix_support"]
ctrlc_support = ["ctrlc"]
env_logger_support = ["env_logger"]
# needed for Unix signals on `Command`s
nix_support = ["nix"]
