[package]
name = "super_orchestrator"
version = "0.1.0"
edition = "2021"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/super_orchestrator"
documentation = "https://docs.rs/super_orchestrator"
description = "WIP container management"
publish = false

[dependencies]
clap = { version = "4.2", features = ["derive"] }
ctrlc = { version = "3.0", optional = true, default-features = false }
env_logger = { version = "0.10", optional = true, default-features = false }
log = "0.4"
musli = "0.0.49"
musli-descriptive = { version = "0.0.49", features = ["std"] }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.9", optional = true }
sha3 = "0.10"
stacked_errors = { path = "../stacked_errors", default-features = false, features = ["tokio_rt_support"] }
tokio = { version = "1.28", features = ["full"] }

[features]
default = ["serde_json_support", "ctrlc_support", "env_logger_support", "serde_yaml_support"]
serde_json_support = ["serde_json"]
ctrlc_support = ["ctrlc", "stacked_errors/ctrlc_support"]
env_logger_support = ["env_logger"]
serde_yaml_support = ["serde_yaml"]
