[package]
name = "super_orchestrator"
version = "0.0.0"
edition = "2021"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/super_orchestrator"
documentation = "https://docs.rs/super_orchestrator"
description = "WIP container management"
publish = false

[dependencies]
clap = { version = "4.2", features = ["derive"] }
ctrlc = { version = "3.0", optional = true, default-features = false }
env_logger = { version = "0.10", optional = true, default-features = false }
log = "0.4"
musli = "0.0.49"
musli-descriptive = { version = "0.0.49", features = ["std"] }
ron = { version = "0.8", optional = true, default-features = false }
serde_json = { version = "1.0", optional = true }
sha3 = "0.10"
thiserror = "1.0"
tokio = { version = "1.28", features = ["full"] }
toml = { version = "0.7", optional = true }
serde_yaml = { version = "0.9", optional = true }

[features]
default = ["serde_json_support", "ron_support", "ctrlc_support", "env_logger_support", "toml_support", "serde_yaml_support"]
serde_json_support = ["serde_json"]
ron_support = ["ron"]
ctrlc_support = ["ctrlc"]
env_logger_support = ["env_logger"]
toml_support = ["toml"]
serde_yaml_support = ["serde_yaml"]
