[package]
name = "super_orchestrator"
version = "0.0.0"
edition = "2021"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/super_orchestrator"
documentation = "https://docs.rs/super_orchestrator"
description = "WIP container management"
publish = false

[dependencies]
clap = { version = "4.2", features = ["derive"] }
ctrlc = { version = "3.0", optional = true, default-features = false }
log = "0.4"
ron = { version = "0.8", optional = true, default-features = false }
serde_json = { version = "1.0", optional = true }
thiserror = "1.0"
tokio = { version = "1.28", features = ["full"] }

[features]
default = ["serde_json_support", "ron_support", "ctrlc_support"]
serde_json_support = ["serde_json"]
ron_support = ["ron"]
ctrlc_support = ["ctrlc"]
